#pragma once

#define CAN_SWERVE_DRIVE_FR 2
#define CAN_SWERVE_DRIVE_FL 3
#define CAN_SWERVE_DRIVE_BR 4
#define CAN_SWERVE_DRIVE_BL 5

#define CAN_SWERVE_ROTATION_FR 6
#define CAN_SWERVE_ROTATION_FL 7
#define CAN_SWERVE_ROTATION_BR 8
#define CAN_SWERVE_ROTATION_BL 9

#define CAN_SWERVE_CANCODER_FR 10
#define CAN_SWERVE_CANCODER_FL 11
#define CAN_SWERVE_CANCODER_BR 12
#define CAN_SWERVE_CANCODER_BL 13

#define CAN_PIGEON 14